# Generated by Django 6.1 on 2026-08-17 07:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Группа турниров',
                'verbose_name_plural': 'Группы турниров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('X', 'Смешанный')], max_length=1, verbose_name='Пол')),
                ('tournament_type', models.CharField(choices=[('LEAGUE', 'Лига (круговая система, до 3 побед в партиях)'), ('SHORT', 'Короткий турнир (до 2 побед в партиях)')], default='LEAGUE', max_length=20, verbose_name='Тип турнира')),
                ('number_of_rounds', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество кругов')),
                ('has_playoff', models.BooleanField(default=False, verbose_name='Плейофф')),
                ('playoff_teams', models.IntegerField(blank=True, choices=[(4, '4 команды'), (8, '8 команд')], null=True, verbose_name='Команд в плейофф')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('applications_open', models.BooleanField(default=True, verbose_name='Приём заявок открыт')),
                ('teams', models.ManyToManyField(blank=True, related_name='tournaments', to='teams.team', verbose_name='Команды')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournament.tournamentgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_applications', to=settings.AUTH_USER_MODEL, verbose_name='Кем подана')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_tournament_applications', to=settings.AUTH_USER_MODEL, verbose_name='Кем обработана')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_applications', to='teams.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tournament.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Заявка на турнир',
                'verbose_name_plural': 'Заявки на турнир',
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TournamentTeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='teams.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='tournament.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Состав команды на турнир',
                'verbose_name_plural': 'Составы команд на турнир',
                'ordering': ['tournament', 'team'],
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('stage', models.CharField(choices=[('PRELIMINARY', 'Предварительный этап'), ('REGULAR', 'Регулярный тур'), ('QUARTER', '1/4 финала'), ('SEMI', '1/2 финала'), ('THIRD', 'Матч за 3 место'), ('FINAL', 'Финал')], max_length=20, verbose_name='Этап')),
                ('round_number', models.IntegerField(blank=True, null=True, verbose_name='Номер тура')),
                ('sets_a', models.IntegerField(blank=True, null=True, verbose_name='Сеты команды А')),
                ('sets_b', models.IntegerField(blank=True, null=True, verbose_name='Сеты команды Б')),
                ('set_scores', models.JSONField(blank=True, default=list, null=True, verbose_name='Счет по сетам')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершен')),
                ('protocol_code', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Код протокола')),
                ('protocol_code_active', models.BooleanField(default=False, verbose_name='Код протокола активен')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='teams.team', verbose_name='Команда А')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='teams.team', verbose_name='Команда Б')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament', verbose_name='Турнир')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.venue', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['date_time', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='StandingsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0, verbose_name='Игры')),
                ('won', models.IntegerField(default=0, verbose_name='Победы')),
                ('lost', models.IntegerField(default=0, verbose_name='Поражения')),
                ('sets_won', models.IntegerField(default=0, verbose_name='Выигранные сеты')),
                ('sets_lost', models.IntegerField(default=0, verbose_name='Проигранные сеты')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings_cache', to='tournament.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Турнирная таблица',
                'verbose_name_plural': 'Турнирные таблицы',
                'ordering': ['-points', '-sets_won'],
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TournamentApplicationPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Игровая позиция')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.tournamentapplication', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_application_entries', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игрок в заявке',
                'verbose_name_plural': 'Игроки в заявке',
                'unique_together': {('application', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRosterPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_players', to='tournament.tournamentteamroster', verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Игрок состава',
                'verbose_name_plural': 'Игроки состава',
                'ordering': ['player__full_name'],
                'unique_together': {('roster', 'player')},
            },
        ),
    ]
