# Generated by Django 5.0.4 on 2026-01-19 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('gender', models.CharField(choices=[('M', 'Мужская'), ('F', 'Женская')], max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name', 'gender'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Группа турниров',
                'verbose_name_plural': 'Группы турниров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('tournament_type', models.CharField(choices=[('LEAGUE', 'Лига (круговая система)')], default='LEAGUE', max_length=20, verbose_name='Тип турнира')),
                ('number_of_rounds', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество кругов')),
                ('has_playoff', models.BooleanField(default=False, verbose_name='Плейофф')),
                ('playoff_teams', models.IntegerField(blank=True, choices=[(4, '4 команды'), (8, '8 команд')], null=True, verbose_name='Команд в плейофф')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('teams', models.ManyToManyField(blank=True, related_name='tournaments', to='tournament.team', verbose_name='Команды')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournament.tournamentgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('stage', models.CharField(choices=[('PRELIMINARY', 'Предварительный этап'), ('REGULAR', 'Регулярный тур'), ('QUARTER', '1/4 финала'), ('SEMI', '1/2 финала'), ('THIRD', 'Матч за 3 место'), ('FINAL', 'Финал')], max_length=20, verbose_name='Этап')),
                ('round_number', models.IntegerField(blank=True, null=True, verbose_name='Номер тура')),
                ('sets_a', models.IntegerField(blank=True, null=True, verbose_name='Сеты команды А')),
                ('sets_b', models.IntegerField(blank=True, null=True, verbose_name='Сеты команды Б')),
                ('set_scores', models.JSONField(blank=True, default=list, null=True, verbose_name='Счет по сетам')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершен')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='tournament.team', verbose_name='Команда А')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='tournament.team', verbose_name='Команда Б')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament', verbose_name='Турнир')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.venue', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['date_time', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='StandingsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0, verbose_name='Игры')),
                ('won', models.IntegerField(default=0, verbose_name='Победы')),
                ('lost', models.IntegerField(default=0, verbose_name='Поражения')),
                ('sets_won', models.IntegerField(default=0, verbose_name='Выигранные сеты')),
                ('sets_lost', models.IntegerField(default=0, verbose_name='Проигранные сеты')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings_cache', to='tournament.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Турнирная таблица',
                'verbose_name_plural': 'Турнирные таблицы',
                'ordering': ['-points', '-sets_won'],
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
