# Generated by Django 6.1 on 2026-08-17 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('gender', models.CharField(choices=[('M', 'Мужская'), ('F', 'Женская'), ('X', 'Смешанная')], max_length=1, verbose_name='Пол')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='Логотип')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('DISBANDED', 'Роспущена'), ('BANNED', 'Забанена')], default='ACTIVE', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ban_reason', models.TextField(blank=True, verbose_name='Причина бана')),
                ('banned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата бана')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name', 'gender'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(blank=True, max_length=254, verbose_name='Email приглашённого')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отклонено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=12, verbose_name='Статус')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Кто пригласил')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённый пользователь')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Приглашение в команду',
                'verbose_name_plural': 'Приглашения в команду',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(default=list, verbose_name='Роли')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное участие')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие в команде',
                'verbose_name_plural': 'Участия в командах',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('team', 'user'), name='uniq_active_team_membership')],
            },
        ),
    ]
